function aa(a,c,e,k,g){function r(b,d){x=x.replace(T[b],"&dbg"+b+"="+d)}function p(b,d){if(b instanceof Array){for(var l=0,n=b.length;l<n;l++)b[l]=b[l]+"="+d;return"&"+b.join("&")}return"&"+b+"="+d}var t=new H,f=g&&g.dvObj||window.$dv,v=g&&"undefined"!==typeof g.billable||f&&f.tags[$uid]&&f.tags[$uid].billable,q=g&&g.impressionId||window.$uid,m=window.Lf||k,h=Array(m.eb),d=m.Ua/m.Zb+1,b=null,n="";a=a?a:null;e=e?e:"";var l="",w=null,y=0,P=new RegExp(/&strp=[^&]*/),U=new RegExp(/&narme=[^&]*/),V=new RegExp(/&narm=[^&]*/),
da=new RegExp(/&naral=[^&]*/),ea=new RegExp(/&evid=[^&]*/);k=new RegExp(/&jsver=[^&]*/);for(var I=new RegExp(/&vct=[^&]*/),T=[new RegExp(/&dbg0=[^&]*/),new RegExp(/&dbg1=[^&]*/),new RegExp(/&dbg2=[^&]*/),new RegExp(/&dbg3=[^&]*/),new RegExp(/&dbg4=[^&]*/),new RegExp(/&dbg5=[^&]*/),new RegExp(/&dbg6=[^&]*/),new RegExp(/&dbg7=[^&]*/),new RegExp(/&dbg8=[^&]*/),new RegExp(/&dbg9=[^&]*/),new RegExp(/&dbg10=[^&]*/),new RegExp(/&dbgtx=[^&]*/)],z=[new RegExp(/&b0=[^&]*/),new RegExp(/&b1=[^&]*/),new RegExp(/&b2=[^&]*/),
new RegExp(/&b3=[^&]*/),new RegExp(/&b4=[^&]*/),new RegExp(/&b5=[^&]*/),new RegExp(/&b6=[^&]*/),new RegExp(/&b7=[^&]*/),new RegExp(/&b8=[^&]*/),new RegExp(/&b9=[^&]*/),new RegExp(/&b10=[^&]*/),new RegExp(/&b11=[^&]*/)],Z=Array(m.eb),u={ea:{D:null,F:null,A:null,v:null,Ke:!1},j:{u:null,s:null,G:null,H:null,B:null,C:null,o:null,m:null,Ke:!1},Xa:{ub:null,tb:null},Bb:0},J="",K="",D,E,L="",M="",N=!1,F="",W=0;W<m.eb;W++)Z[W]="&b"+W+"=";c=function(b,d){if(b&&d)return d.replace(new RegExp(b+"=\\d*[&^#]"),
"")}("prndr",c?c:null);var G=e+"?"+c,G=k.test(G)?G.replace(k,"&jsver="+a):G+"&jsver="+a,x="&naral=&narm=&narme=&dbg2=&dbg3=&dbg4=&dbg5=&dbg6=&dbg7=&dbg8=&dbg9=&dbg10=&dbgtx=&vct=",A="&strp=";c="&ctime="+(new Date).getTime();var O=0,Q="",R="",S=0,B=0,C=0,X=0;this.Rc=function(){return O};this.Kc=G+A+x+c+l+J;setEventId=function(b){w=b;x=x.replace(ea,"&evid="+w)};setAdLocatorIndicator=function(b){S=S|b;x=x.replace(da,"&naral="+S)};setNAPMeasure=function(b){t.a("l2("+b+")");B=B|b;fa()?(setNotApplicableTime(),
O=0):0==O&&(O=(new Date).getTime());x=x.replace(V,"&narm="+B);t.a("l2e")};setNAPMeasureErr=function(b){C=C|b;x=x.replace(U,"&narme="+C)};this.qd=function(b){X=X|b;x=x.replace(I,"&vct="+X)};setBuckectStr=function(b,d){d?l=l.replace(z[b],"&b"+b+"="+h[b]):l=l+"&b"+b+"="+h[b]};setNotApplicableTime=function(){0!=O&&(Q=(new Date).getTime()-O)};getBucketString=function(){return l};getFraudNonFraudEvents=function(b,d,l){return N?p(d,l):p(b,l)};this.kc=function(){return N};this.pd=function(d){b=d;A=A.replace(P,
"&strp="+b);this.pd=function(){}};this.jb=function(){return(new Date).getTime()};var ga=this.jb();this.we=function(){return ga};this.uf=function(){N=!0};this.sf=function(b,d){F+="&"+d.reportQueryString.viewrate+"="+b[d.serverProperties.viewedRate]+"&"+d.reportQueryString.error+"="+b[d.serverProperties.error]+"&"+d.reportQueryString.projected+"="+(1==b[d.serverProperties.viewed]?2:b[d.serverProperties.projected]);if("undefined"===typeof b[d.serverProperties.featurebit]||b[d.serverProperties.featurebit]&&
1==b[d.serverProperties.featurebit])F+="&"+d.reportQueryString.measurems+"=0",1==b[d.serverProperties.viewed]&&(F+="&"+d.reportQueryString.viewedms+"=0")};this.ff=function(){B=B&-3;C=C&-2;C&=-3};this.wb=function(){setNAPMeasure(2)};this.qf=function(){setNAPMeasureErr(8);this.rc()};this.rc=function(){setNAPMeasure(4)};this.ld=function(){setAdLocatorIndicator(8);this.wb()};this.wd=function(b){setAdLocatorIndicator(16);r(9,b)};this.xd=function(){setAdLocatorIndicator(1)};this.nf=function(){this.wb();
setNAPMeasureErr(1)};this.mf=function(){this.wb();setNAPMeasureErr(2)};this.qc=function(b,d){setNAPMeasure(8);R=t.bc(b,d)};this.jf=function(){t.a("l1");B=B&-3;setNAPMeasure(1);t.a("l1e")};this.od=function(){setNAPMeasure(16)};this.me=function(){return h};this.md=function(b,l){t.a("ie15");if(0<=b.i){var n=Math.floor(b.i/m.Zb);0<b.i%m.Zb?n++:0<b.i&&n++;isNaN(h[n])&&(h[n]=0);h[n]+=l;b.J&&n>=d||0==b.J&&6<=n?y+=l:y=0}t.a("ie15e")};this.ye=function(){for(var b=0,d=0;d<h.length;d++)h[d]&&(b+=h[d]);return b};
this.lf=function(b){var d=N?"false":b.Yc;b="&advisonl="+(null==b.Yc?"":d)+("&adabvvponl="+(null==b.Xc?"":b.Xc));r(8,"CSS1Compat"===document.compatMode?1:0);t.a("ff52");void 0!=document.documentMode&&null!=document.documentMode&&r(10,document.documentMode);t.a("ff52e");J=b};this.Ya=function(b){t.a("ie14");M="&adbtftopg="+(null==b?"":N?"true":b)};this.kf=function(b){null!=b&&(u=b)};this.nd=function(b){t.a("ie19");this.kf(b.K);this.tf();t.a("ie19e")};this.Ad=function(){var b;b="&vptoscrx="+(null!=u.ea.D?
Math.round(u.ea.D):"");b+="&vptoscry="+(null!=u.ea.F?Math.round(u.ea.F):"");b+="&vpwdth="+(null!=u.ea.A?Math.round(u.ea.A):"");b+="&vphgt="+(null!=u.ea.v?Math.round(u.ea.v):"");b+="&adtovpx="+(null!=u.j.u?Math.round(u.j.u):"");b+="&adtovpy="+(null!=u.j.s?Math.round(u.j.s):"");b+="&adtopgx="+(null!=u.j.G?Math.round(u.j.G):"");b+="&adtopgy="+(null!=u.j.H?Math.round(u.j.H):"");b+="&adtoscrx="+(null!=u.j.B?Math.round(u.j.B):"");b+="&adtoscry="+(null!=u.j.C?Math.round(u.j.C):"");b+="&scrwdth="+(null!=
u.Xa.ub?Math.round(u.Xa.ub):"");b+="&scrhgt="+(null!=u.Xa.tb?Math.round(u.Xa.tb):"");return b+="&almesind="+u.Bb};this.Bd=function(){var b="";if(D&&E){var d=null!=u.j.o?u.j.o:null,l=null!=u.j.m?u.j.m:null;0>D*E&&(b+="&dvp_adwdth="+D,b+="&dvp_adhgt="+E,D=d,E=l)}else D=null!=u.j.o?u.j.o:null,E=null!=u.j.m?u.j.m:null;b+="&adwdth="+(null!=D?D:"");return b+="&adhgt="+(null!=E?E:"")};this.tf=function(){setNotApplicableTime();l="";for(var b=0;b<h.length;b++)h[b]&&(l+=Z[b]+h[b]);K=this.Bd();L=J+this.Ad()+
K;L+=M;this.Kc=G+A+x+l+L};this.Pc=function(){return 1E3<=y};this.ca=function(b){var d=G+"&impid="+q,a=-1,m=t.mb();f&&f.tags[q]&&f.tags[q].getTimeDiff&&(a=f.tags[q].getTimeDiff());switch(b){case 1:n=a;d+=A+x+"&napt="+Q+L+m+"&napr="+R;m="";v&&(m=g.Ta?getFraudNonFraudEvents(["isbmms"],"isfbmms",a):getFraudNonFraudEvents(["isbmms","isgmmims"],"isfbmms",a));d+=m+getFraudNonFraudEvents("ismms","isfmms",a)+"&isumms="+a;break;case 2:d+=A+x+"&napt="+Q+L+m+"&napr="+R+getFraudNonFraudEvents("isnmms","isfnmms",
a);break;case 3:d+="&istoms="+a;case 4:case 8:d+=A+M+K+"&isbxdms="+a+(N?"&fbxdtb="+this.ye():l);break;case 5:n=n||a;d+=A+M+K+J+getFraudNonFraudEvents("isiabvms","isfiabvms",a)+"&isuiabvms="+a+getFraudNonFraudEvents("ismms","isfmms",n)+"&isumms="+n;break;case 6:n=n||a;d+=M+K+J+getFraudNonFraudEvents("iscvmvms","isfcvmvms",a)+getFraudNonFraudEvents("ismms","isfmms",n);break;case 16:d+=A+x+"&napt="+Q+m+"&napr="+R+"&ishems="+a;break;case 7:return d;case 9:d+=F;break;case 10:d+="&ismms=0";break;case 17:n=
n||a;m=g.Ta?["isbmms"]:["isbmms","isgmmims"];d+=A+M+K+J+getFraudNonFraudEvents(g.Ta?["isbvms"]:["isbvms","isgmpims"],"isfbvms",a)+getFraudNonFraudEvents(m,"isfbmms",n);break;default:d=this.Kc+"&napt="+Q+"&ctime="+this.jb()+m+"&napr="+R}return d+"&evid="+b+"&ctime="+this.jb()};this.le=function(){t.a("ie17");for(var b=[],d=0;d<m.eb;d++)b[d]=h[d]?h[d]:0;return b};var fa=this.Rb=function(){return 2==(B&2)&&8!=(S&8)||4==(B&4)||8==(C&8)&&8==(S&8)?!1:!0};this.af=function(b){t.a("l3");b=t.na(b);t.a("cm3e");
b&&(r(5,b.w),r(6,b.h));t.a("l3e")};return this}
function ba(a,c){this.window=null;this.hb={};this.images={};this.Ub=function(a){var c=this.window.document.createElement("img");c.name=c.id=a;c.width=0;c.height=0;c.style.display="none";c.src="";this.window.document.body.insertBefore(c,this.window.document.body.firstChild);return c};this.tc=function(a,c){if(c&&1!=this.hb[c]||16==c)this.images[c].src=a,this.hb[c]=1};this.$=function(a,c){if(c&&1!=this.hb[c]||16==c||7==c)this.window.document.createElement("img").src=a,this.hb[c]=1};if(this.window=a)this.images=
{3:this.Ub(c+"_13"),4:this.Ub(c+"_14"),8:this.Ub(c+"_18")};return this}function ca(){this.tc=function(){};this.$=function(){}}
function ha(a,c,e,k){function g(){if(1==w){try{for(var b in n)l.removeChild(n[b]);d.document.body.removeChild(l)}catch(a){}w=!1}}function r(b){b=b||0;var d=f(0);d.bd()?7<d.lb()?(g(),P=y=w=!1):(w=!0,y=!1):20>b?(b++,setTimeout(r,50,b)):(w=y=P=!1,g())}function p(b){$dv&&$dv.tags&&$dv.tags[k]&&$dv.tags[k].getTimeDiff&&$dv.tags[k].getTimeDiff();if(null!==b.bb)for(var d=0;d<b.bb.length;d++){var l=f(d).lb();0==d?l>U&&(U=l):l>V&&(V=l)}}function t(b){for(var d=!0,l=0;13>=l;l++)var n=f(l),d=d&(null!==n&&n.bd());
if(!d)return null;b.Fc=0;b.nc=0;b.mc=0;b.hc=0;b.Ba=0;b.bb=Array(13);d=f(0).lb();for(l=1;13>=l;l++)if(n=5<Math.abs(f(l).lb()-d),b.bb[l]=n)switch(b.Fc++,l){case 2:case 3:case 4:case 5:b.nc++;break;case 6:case 7:case 8:case 9:b.mc++;break;case 10:case 11:case 12:case 13:b.hc++}if(13===b.Fc)return b.Ba=100,p(b),!0;d=b.bb;if(!1===d[1]){if(3<=b.hc||3<=b.mc||3<=b.nc)return p(b),null;b.Ba=0;p(b);return!1}if(!0===d[1]&&(!0===d[2]&&!0===d[3]||!0===d[2]&&!0===d[4]||!0===d[3]&&!0===d[5]||!0===d[4]&&!0===d[5])||
!0===d[1]&&4==b.mc||!0===d[1]&&4==b.hc&&1<=b.nc)return b.Ba=50,p(b),!0;if(d[2]&&d[5]&&!(d[6]&&d[10]&&d[1]&&d[13]&&d[9])||d[4]&&d[3]&&!(d[8]&&d[12]&&d[1]&&d[11]&&d[7]))return p(b),null;b.Ba=0;p(b);return!1}function f(b){b=n[b];var d=null;b&&(d=b.contentWindow);return d}function v(){for(var d=b.getBoundingClientRect(),l=d.width,a=d.height,c=l/(1+m),w=a/(1+m),q=l/m,v=a/m,e=0;13>=e;e++){var h=d.left,f=d.top;switch(e){case 0:f=h=-1E5;break;case 1:h+=(l-1)/2;f+=(a-1)/2;break;case 3:h+=l-1;break;case 4:f+=
a-1;break;case 5:h+=l-1;f+=a-1;break;case 6:h+=(l-q)/2;f+=(a-v)/2;break;case 7:h+=(l-q)/2+q;f+=(a-v)/2;break;case 8:h+=(l-q)/2;f+=(a-v)/2+v;break;case 9:h+=(l-q)/2+q;f+=(a-v)/2+v;break;case 10:h+=(l-c)/2;f+=(a-w)/2;break;case 11:h+=(l-c)/2+c;f+=(a-w)/2;break;case 12:h+=(l-c)/2;f+=(a-w)/2+w;break;case 13:h+=(l-c)/2+c,f+=(a-w)/2+w}6<=e&&(h-=.5,f-=.5);var g=n[e];g.style.left=h+"px";g.style.top=f+"px"}}function q(){if(null!=b&&null!=b.parentNode){y=!0;l=d.document.createElement("div");d.document.body.appendChild(l);
for(var a=0;13>=a;a++){var m=d.document.createElement("iframe");m.width=1;m.height=1;m.style.position="absolute";m.frameBorder="0";m.style.visibility="hidden";m.style.zIndex=-9999999;m.style.display="block";m.src="javascript:no=false;yes=true;("+function(){window.Se={Xd:100};window.Mc=no;window.$a=0;window.Nc=0;window.Wc=0;window.Mf=no;window.lb=function(){return window.Wc};window.bd=function(){return window.Mc};window.Qe=window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||
window.msRequestAnimationFrame;window.Qb=function(){window.$a++;window.Qe(window.Qb,document)};window.Qb();setInterval(function(){10>window.$a&&window.Qb();window.Wc=window.$a-window.Nc;window.Nc=window.$a},window.Se.Xd);window.setTimeout(function(){window.Mc=yes},250)}.toString()+")();";l.appendChild(m);n.push(m)}v()}}var m=Math.sqrt(2),h=new H,d=null,b=null,n=[],l,w=!1,y=!1,P=h.rb(a,c,e),U=0,V=0;this.Ie=function(){0==y&&(0==(this.Sa()&&(null!=b&&h.$c(b,d)?!0:!1))?w=!1:(q(),r()))};this.Sa=function(){return P};
this.Ne=function(){return w};this.rd=function(l,n){d=l;b=n;this.Ie()};this.Ae=function(){if(0==w)return null;var b={};return null==t(b)?null:b.Ba}}
function ia(a,c,e,k,g,r,p,t){this.b=new H;this.window=a;this.f=c;this.O=e;this.I=k;this.W=p&&p.Enums.BrowserId||window.$dv.Enums.BrowserId;this.X=p&&p.Enums.TrafficScenario||window.$dv.Enums.TrafficScenario;this.P=g;this.fc=r;this.ga=null;this.ga=new ha(this.O,this.I,p,t);null!=this.ga&&this.ga.Sa()&&this.ga.rd(this.window,this.f);this.nb=this.sb=this.ra=null;this.ob=!1;var f=0;this.ia={Nd:1,Od:2,Hd:4,Hb:8,Gd:16,Ib:32,Md:64};this.pc=function(a,c,m,h){if(h&&h.insertBefore&&h.firstChild&&(a=this.window.document.createElement(a))){for(var d in c)a[d]=
c[d];for(d in m)a.style[d]=m[d];h.insertBefore(a,h.firstChild);return a}return null};this.ac=function(a,c,m){var h=c.A;c=c.v;var d=0,b=0,n=a.right-a.left,l=a.bottom-a.top;if(0>a.bottom||0>a.right||a.top>c||a.left>h||0>=n||0>=l)return 0;0>a.top?Math.abs(a.top)>=l?d=l:(d=l+a.top,d>c&&(d=c)):d=a.top+l>c?c-a.top:l;0>a.left?Math.abs(a.left)>=n?b=n:(b=n+a.left,b>h&&(b=h)):b=a.left+n>h?h-a.left:n;return 0>=b||0>=d?0:Math.round(b*d/(n*l)*(m?n*l/((m.right-m.left)*(m.bottom-m.top)):1)*100)};this.$b=function(a,
c){try{var m={x:a.offsetLeft,y:a.offsetTop};if(a.offsetParent){var h=this.$b(a.offsetParent,c);m.x+=h.x;m.y+=h.y}else c!=c.parent&&this.b.Jb(c,c.parent)&&(h=this.$b(c.frameElement,c.parent),m.x+=h.x,m.y+=h.y);return m}catch(d){return{x:null,y:null}}};this.oa=function(a){if(this.O==this.X.CrossDomain)if(this.b.wa(this.window)&&this.window.$sf.ext.geom)this.oa=function(){var b=this.window.$sf.ext.geom(),d=window.outerHeight||this.window.document.documentElement.clientHeight?this.window.outerHeight-
parseInt(b.win.h):this.P.Explorer.Y,a={A:null,v:null,D:null,F:null,g:!1};a.A=parseInt(b.win.w);a.v=parseInt(b.win.h);a.D=parseInt(b.win.l);a.F=parseInt(b.win.t)+d;a.g=!0;return a};else if(this.I.V==this.W.Firefox)this.oa=function(){var b=8==screen.top-this.window.screenY&&8==screen.left-this.window.screenX,d=b?0:this.window.screenX-screen.left,b=b?0:this.window.screenY-screen.top,a={A:null,v:null,D:null,F:null,g:!1};a.A=this.window.outerWidth;a.v=this.window.outerHeight-this.P.Firefox.Y;a.D=d;a.F=
b+this.P.Firefox.Y;a.g=!0;return a};else if(this.b.jc(this.window)){var c=this;this.window.context.observeIntersection(function(b){b.forEach(function(b){c.ra=b})});this.oa=function(){var b={A:null,v:null,g:!1,D:null,F:null};null!=this.ra?(b.A=this.ra.rootBounds.width,b.v=this.ra.rootBounds.height):(b.A=0,b.v=0);b.g=!0;return b}}else if(this.I.V==this.W.IE&&/^[11|12]/.test(this.I.va))this.oa=function(){var b=-8==this.window.screenY&&-8==this.window.screenX,d=b?0:this.window.screenX,b=b?0:this.window.screenY,
a={A:null,v:null,D:null,F:null,g:!1};a.A=this.window.outerWidth;a.v=this.window.outerHeight-this.P.Explorer.Y;a.D=d;a.F=b+this.P.Explorer.Y;a.g=!0;return a};else if(this.I.V==this.W.IE&&/[6-9]|[10]/.test(this.I.va)){var m=this.pc("iframe",{name:"dv_ie9onload",src:"",width:0,height:0,fe:0,Te:"0",Ue:"0"},{display:"inline",position:"absolute",top:0,left:0,zf:"none",zIndex:0,border:0},this.window.document.body),h=this.pc("iframe",{name:"dv_ie9onmousemove",src:"",width:0,height:0,fe:0,Te:"0",Ue:"0"},{display:"inline",
position:"absolute",top:0,left:0,zf:"none",zIndex:0,border:0},this.window.document.body),d=h.contentWindow||h.window||h.contentDocument.window||h.contentWindow.window||this.window.Cf,b=m.contentDocument||m.contentWindow.document,m=h.contentDocument||h.contentWindow.document,n="<html><head><script >window.onload = "+function(b){b&&(window.event=b);isFinite(String(window.event.clientY))&&(parent.Oa={Mb:window.event.clientY,Lb:window.event.clientX,zd:window.event.screenY-window.event.clientY-window.screenY})}.toString()+
"; \x3c/script></head><body></body></html>",h='<html><head></head><body><script > function runMoM(){ window.document.body.fireEvent("onmousemove");} window.document.body.onmousemove = '+function(b){b&&(window.event=b);isFinite(String(window.event.clientY))&&(parent.sa={Mb:window.event.clientY,Lb:window.event.clientX,Ea:window.event.screenY-window.event.y,Da:window.event.screenX-window.event.x})}.toString()+"; runMoM();\x3c/script></body></html>";m.open("text/html","replace");m.write(h);m.close();
b.open("text/html","replace");b.write(n);b.close();("CSS1Compat"===document.compatMode?this.window.document.documentElement:this.window.document.body).clientLeft;this.oa=function(){d.runMoM();b.open("text/html","replace");b.write(n);b.close();var l=this.window.sa,a=this.window.Oa,m=screen.availWidth,c=screen.availHeight,a=a?a.zd:this.P.Explorer.Y;if(l){var h=l.Da,f=l.Ea;l.Da>=m&&(l.Da-=m);l.Ea>=c&&(l.Ea-=c);var q={A:null,v:null,D:null,F:null,g:!1};q.A=this.window.outerWidth?this.window.outerWidth-
20:m-l.Da-20;q.v=this.window.outerHeight?this.window.outerHeight-a-10:c-l.Ea-10;q.D=h;q.F=f;q.g=!0}else q={A:null,v:null,D:null,F:null,g:!1},q.A=this.window.outerWidth?this.window.outerWidth-20:m-20,q.v=this.window.outerHeight?this.window.outerHeight-a-10:c-10,q.D=null,q.F=null,q.g=!1;return q}}else this.b.qb()?(this.jd(),this.oa=function(){this.ob||this.jd();var b={A:null,v:null,D:null,F:null,g:!1};b.A=this.window.outerWidth;b.v=this.window.outerHeight-this.P.Chrome.Y;b.g=!1;return b}):this.oa=this.I.V==
this.W.Chrome?function(){var b={A:null,v:null,D:null,F:null,g:!1},d=!1;try{b.A=this.window.frameElement.offsetParent.parentNode.clientWidth,b.v=this.window.frameElement.offsetParent.parentNode.clientHeight,d=!0}catch(a){}b.D=this.window.screenX;b.F=this.window.screenY;b.g=d;return b}:null!=this.ga&&this.ga.Sa()?function(){var b={A:null,v:null,D:null,F:null,g:!1};b.A=this.window.outerWidth;b.v=this.window.outerHeight-this.P.Safari.Y;b.g=!1;return b}:function(){return{A:null,v:null,D:null,F:null,g:!1}};
else this.oa=function(){var b,d,a=this.window.top;void 0!=a.mozInnerScreenX&&null!=a.mozInnerScreenX?(b=a.mozInnerScreenX,d=a.mozInnerScreenY):void 0!=a.screenX&&null!=a.screenX?0!=a.screenLeft+8&&a.screenLeft+8!=screen.width||0!=a.screenTop+8&&a.screenTop+8!=screen.height?(b=a.screenLeft,d=a.screenTop+(a.outerHeight-a.innerHeight)):(b=a.screenLeft+8,d=a.screenTop+(a.outerHeight-a.innerHeight)+8):(b=a.screenLeft,d=a.screenTop);var n={A:null,v:null,D:null,F:null,g:!1},m=this.b.Qa(a);n.A=a.innerWidth||
m.clientWidth;n.v=a.innerHeight||m.clientHeight;n.D=b;n.F=d;n.g=!0;return n};return this.oa(a)};this.ma=function(a,c){f=1;this.O==this.X.CrossDomain?this.b.wa(this.window)&&this.window.$sf.ext.geom&&this.window.$sf.ext.geom().par?(f=8,this.ma=function(){var a=this.window.$sf.ext.geom(),c=window.outerHeight||this.window.document.documentElement.clientHeight?this.window.outerHeight-parseInt(a.win.h):this.P.Explorer.Y,d={u:null,s:null,G:null,H:null,B:null,C:null,o:null,m:null,g:!1,rect:null,M:null,qa:null};
d.u=parseInt(a.self.l)-parseInt(a.par.l);d.s=parseInt(a.self.t)-parseInt(a.par.t);d.G=parseInt(a.self.l);d.H=parseInt(a.self.t);d.B=parseInt(a.win.l)+d.u;d.C=parseInt(a.win.t)+d.s+c;d.o=parseInt(a.self.w);d.m=parseInt(a.self.h);d.g=!0;d.rect={top:d.s,bottom:d.s+d.m,left:d.u,right:d.u+d.o};return d}):this.I.V==this.W.Firefox?this.ma=function(){var a=1;window.devicePixelRatio&&(a=window.devicePixelRatio);var c=this.window.screenX,d=this.window.screenY,b=this.window.mozInnerScreenX/a-c,a=this.window.mozInnerScreenY/
a-d-this.P.Firefox.Y,b={left:b,top:a,right:b+this.window.innerWidth,bottom:a+this.window.innerHeight},a={u:null,s:null,G:null,H:null,B:null,C:null,o:null,m:null,g:!1,rect:null,M:null,qa:null};a.u=b.left;a.s=b.top;a.G=null;a.H=null;a.B=c+b.left;a.C=d+b.top;a.o=this.window.innerWidth;a.m=this.window.innerHeight;a.g=!0;a.rect=b;this.b.Ab()&&(a=this.ib(a));return a}:this.b.jc(this.window)?(f=32,this.ma=function(){var a={u:null,s:null,o:null,m:null,g:!1,rect:null,M:null,qa:null,G:null,H:null,B:null,C:null};
null!=this.ra?(a.u=this.ra.boundingClientRect.left,a.s=this.ra.boundingClientRect.top,a.o=this.ra.boundingClientRect.width,a.m=this.ra.boundingClientRect.height):(a.u=0,a.s=0,a.o=0,a.m=0);a.g=!0;a.rect={top:a.s,bottom:a.s+a.m,left:a.u,right:a.u+a.o};return a}):this.I.V==this.W.IE&&/^[11|12]/.test(this.I.va)?this.ma=function(a){var c=this.window.screenLeft-window.screenX,d=this.window.screenTop-window.screenY-this.P.Explorer.Y,c={left:c,top:d,right:c+this.window.innerWidth,bottom:d+this.window.innerHeight},
d={u:null,s:null,G:null,H:null,B:null,C:null,o:null,m:null,g:!1,rect:null,M:null,qa:null};d.u=c.left;d.s=c.top;d.G=null;d.H=null;d.B=a.D+c.left;d.C=a.F+c.top;d.o=this.window.innerWidth;d.m=this.window.innerHeight;d.g=!0;d.rect=c;this.b.Ab()&&(d=this.ib(d));return d}:this.I.V==this.W.IE&&/[6-9]|[10]/.test(this.I.va)?this.ma=function(){if(8==document.documentMode)return{u:null,s:null,G:null,H:null,B:null,C:null,o:null,m:null,g:!1,rect:null,M:null,qa:null};var a=this.window.Oa&&this.window.sa?this.window.Oa.Mb-
this.window.sa.Mb:0,c=this.window.Oa&&this.window.sa?this.window.Oa.Lb-this.window.sa.Lb:0,d=this.b.Qa(this.window),b={u:null,s:null,G:null,H:null,B:null,C:null,o:null,m:null,g:!1,rect:null,M:null,qa:null};b.u=c;b.s=a;b.G=null;b.H=null;b.B=this.window.sa?c+this.window.sa.Da:null;b.C=this.window.sa?a+this.window.sa.Ea:null;b.o=this.window.innerWidth||d.clientWidth;b.m=this.window.innerHeight||d.clientHeight;b.g=!0;b.rect={left:c,top:a,right:c+(this.window.innerWidth||d.clientWidth),bottom:a+(this.window.innerHeight||
d.clientHeight)};this.b.Ab()&&(b=this.ib(b));return b}:this.b.qb()?(f=512,this.ma=function(){var a={u:null,s:null,G:null,H:null,B:null,C:null,o:null,m:null,g:!1,rect:null,M:null,qa:null};null!=this.f&&(adData=this.b.kb(this.f),a.o=adData?adData.w:this.window.innerWidth,a.m=adData?adData.h:this.window.innerHeight);return a}):this.ma=this.I.V==this.W.Chrome?function(){var a=null,c=null,d=!1;try{var b=this.window.frameElement.offsetTop,a=this.window.frameElement.offsetLeft-this.window.frameElement.offsetParent.scrollLeft,
c=b-this.window.frameElement.offsetParent.scrollTop,d=!0}catch(n){}b={u:null,s:null,G:null,H:null,B:null,C:null,o:null,m:null,g:!1,rect:null,M:null,qa:null};b.u=a;b.s=c;b.G=null;b.H=null;b.B=null;b.C=null;b.o=this.window.innerWidth;b.m=this.window.innerHeight;b.g=d;b.rect=d?{left:a,top:c,right:a+this.window.innerWidth,bottom:c+this.window.innerHeight}:null;this.b.Ab()&&(b=this.ib(b));return b}:null!=this.ga&&this.ga.Sa()?function(){var a={u:null,s:null,G:null,H:null,B:null,C:null,o:null,m:null,g:!1,
rect:null,M:null,qa:null};null!=this.f&&(adData=this.b.kb(this.f),a.o=adData?adData.w:this.window.innerWidth,a.m=adData?adData.h:this.window.innerHeight);return a}:function(){return{u:null,s:null,G:null,H:null,B:null,C:null,o:null,m:null,g:!1,rect:null,M:null,qa:null}}:this.ma=function(a){var c=this.$b(this.f,this.window),d={u:null,s:null,G:null,H:null,B:null,C:null,o:null,m:null,g:!1,rect:null,M:null,qa:null},b=this.b.cc(this.f,this.window),n=this.b.yc(this.f,this.window);d.u=n.left;d.s=n.top;d.G=
c.x;d.H=c.y;d.B=a.D+n.left;d.C=a.F+n.top;d.o=n.w;d.m=n.h;d.g=!0;d.rect=b;d.M=n;return d};return this.ma(a,c)};this.ib=function(a){if(this.window.document.body==this.f||this.window.document.documentElement==this.f)return a;var c=this.b.kb(this.f);if(c){var f=c.w,e=c.h,d=a.u,b=a.s,n=a.C,l=a.B;null!=a.u&&null!=a.s&&null!=a.m&&null!=a.o&&a.rect&&(0<c.t?(b=a.s+c.t,null!=a.C&&(n=a.C+c.t)):e+=c.t,0<c.l?(d+=c.l,null!=a.B&&(l=a.B+c.l)):f+=c.l,c.r>a.o&&(f-=c.r-a.o),c.Ec>a.m&&(e-=c.Ec-a.m),a.o=0<f?f:0,a.m=0<
e?e:0,a.u=d,a.s=b,a.C=n,a.B=l,a.rect.left=a.u,a.rect.top=a.s,a.rect.right=a.u+c.w,a.rect.bottom=a.s+c.h,a.M={w:f,h:e,left:d,right:d+f,top:b,bottom:b+e})}return a};this.ve=function(){var a=screen.availLeft||0;return{g:$dv.CommonData&&$dv.CommonData.deviceType&&1==$dv.CommonData.deviceType?"undefined"!==typeof a:!1,ub:screen.availWidth||screen.width,tb:screen.availHeight||screen.height,Jf:a,Kf:screen.availTop||0}};this.ie=function(){var a=this.ve(),c=this.oa(a),f=this.ma(c,a);return{ea:c,j:f,Xa:a,Bb:(null==
c.D||null==c.F?0:this.ia.Nd)|(null==c.A||null==c.v?0:this.ia.Od)|(null==f.u||null==f.s?0:this.ia.Hd)|(null==f.G||null==f.H?0:this.ia.Hb)|(null==f.B||null==f.C?0:this.ia.Gd)|(null==f.m||null==f.o?0:this.ia.Ib)|(null==a.tb||null==a.ub?0:this.ia.Md),J:this.Jc(f.m,f.o)}};this.Jc=function(a,c){null==a&&(a=0);null==c&&(c=0);return 242500<=a*c?!0:!1};this.qe=function(){this.b.a("c10");if(null!=this.f)if(this.b.$c(this.f,this.window))try{var a={timeStamp:new Date,i:-3,ja:-3,K:null,J:!1,fa:0};if(!this.fc())return a;
var c=this.ie();if(!c.j.g||!c.ea.g){if(this.b.wa(this.window)&&this.window.$sf.ext.inViewPercentage){var e=this.window.$sf.ext.inViewPercentage();return{timeStamp:new Date,i:e,ja:e,K:c,J:c.J,fa:16}}if(this.b.qb()&&this.ob)return e=0,null!=this.nb&&(e=Math.round(100*this.nb.intersectionRatio)),{timeStamp:new Date,i:e,ja:e,K:c,J:this.Jc(c.j.m,c.j.o),fa:512};if(this.ga.Sa()){var h={timeStamp:new Date,i:-3,ja:-3,K:null,J:!1,fa:2};if(0==this.ga.Ne())h.i=-6,h.ja=-6,this.ga.rd(this.window,this.f);else{var d=
this.ga.Ae();null!=d&&(h.K=c,h.J=c.J,h.i=d,h.ja=d)}return h}a.K=c;f&&(a.fa=f);return a}if(c.j&&c.j.M&&(0===c.j.M.w||1===c.j.M.w||0===c.j.M.h||1===c.j.M.h))return{timeStamp:new Date,i:-5,ja:-5,K:c,fa:f};e=c.j.M?this.ac(c.j.M,c.ea,c.j.rect):this.ac(c.j.rect,c.ea);return{timeStamp:new Date,i:e,ja:e,K:c,J:c.J,fa:f}}catch(b){return{timeStamp:new Date,i:-4,ja:-4,K:null,J:!1,fa:f}}else return{timeStamp:new Date,i:-2,ja:-2,K:null,J:!1,fa:0};else return{timeStamp:new Date,i:-1,ja:-1,K:null,J:!1,fa:0}};this.je=
function(a,c){this.b.a("c11");var f=null,e=null;if(null!=a.K){var d=a.K.j;c<=this.P.Xe&&(f=0<=a.i||-5==a.i?a.J&&a.i>=this.P.Ua||0==a.J&&50<=a.i?!0:!1:null,e=a.J?this.P.Ua/100:.5,e=0==f?0>d.s+d.m*e?!0:!1:1==f?!1:null)}return{Xc:e,Yc:f}};this.pb=function(a){this.b.a("c12");var c=null;if(2!=a.fa&&512!=a.fa&&null!=a.K){var f=a.K.Bb,e=a.K.j;(f&this.ia.Hb)==this.ia.Hb&&(f&this.ia.Ib)==this.ia.Ib&&(c=this.ac({left:e.G,top:e.H,right:e.G+e.o,bottom:e.H+e.m},a.K.ea,e.rect),c=0<=a.i?a.J&&c>=this.P.Ua||0==a.J&&
50<=c?!1:!0:null)}this.b.a("c12e");return c};this.jd=function(){function a(f){f.forEach(function(a){c.nb=a})}var c=this;"undefined"!=typeof IntersectionObserver&&null!=this.f&&(f=512,this.sb=new IntersectionObserver(a,{threshold:[0,.1,.2,.3,.4,.5,.6,.7,.8,.9,1]}),this.sb.observe(this.f),this.ob=!0)};this.He=function(){this.f=null;null!=this.sb&&(this.sb.disconnect(),this.nb=null,this.ob=!1)}}
function H(){this.getElementVolume_object=function(a){var c=a.getAttribute("width"),e=a.getAttribute("height");null==c||""==c||null==e||""==e?(a=a.parentNode,a={w:a.clientWidth,h:a.clientHeight}):a={w:c,h:e};return a};this.Oe=function(a){var c=0;try{for(;null!=a&&10>c;){if("none"==window.getComputedStyle(a).display||"hidden"==window.getComputedStyle(a).visibility)return!1;a=a.parentElement;c++}}catch(e){}return!0};this.na=function(a,c){this.a("cm1");var e=null,k=a.nodeName.toLowerCase();c&&this["getElementVolume_"+
k]&&(e=this["getElementVolume_"+k](a));if(!e&&(e=this.kb(a),this.a("cm2e"),!e||1>=e.w||1>=e.h))return this.a("cm1e"),{w:0,h:0};e.w.indexOf&&e.w.indexOf("px")&&(e.w=e.w.replace("px",""));e.h.indexOf&&e.h.indexOf("px")&&(e.h=e.h.replace("px",""));this.a("cm1e");return e};this.kb=function(a){this.a("cm2");try{var c;return document.body.getBoundingClientRect&&(c=a.getBoundingClientRect())?{w:c.right-c.left,h:c.bottom-c.top,l:c.left,t:c.top,Ec:c.bottom,r:c.right}:null}catch(e){return null}};this.Qa=function(a){this.a("ff8");
a=a.document.documentElement.clientHeight?a.document.documentElement:a.document.body;this.a("ff8e");return a};this.Qc=function(a,c){this.a("ff9");var e=0,k=!1;if(a.document.all)for(var g=0;g<a.document.all.length;g++)"BODY"==a.document.all[g].nodeName&&(k=!0),k&&("width"==c?a.document.all[g].width>e&&(e=a.document.all[g].width):a.document.all[g].height>e&&(e=a.document.all[g].height));this.a("ff9e");return e};this.ed=function(a,c){for(var e=this.Qa(a),k=a.innerWidth||e.clientWidth||this.Qc(a,"width"),
e=a.innerHeight||e.clientHeight||this.Qc(a,"height"),g=c.length,r=0,p=0;p<g;p++)if(15>=Math.abs(k-c[p].w)){r=c[p].h.length;for(k=0;k<r;k++)if(15>=Math.abs(e-c[p].h[k]))return!0;break}return!1};this.vf=function(a){for(var c=[],e=-1;c[++e]=a[e];);c.length--;return c};this.Eb=function(a,c,e,k){var g=a.getElementsByTagName("*"),g=this.vf(g);g.unshift(a);for(var r=["EMBED","IFRAME","OBJECT","IMG","DIV"],p=[],t=0;t<g.length;t++){var f=g[t];if(-1!=r.indexOf(f.nodeName)){var v=k(f);v&&p.push({Dc:v.w*v.h,
w:v.w,h:v.h,type:f.nodeName||"other",ee:f})}}p=p.sort(function(a,c){return c.Dc-a.Dc||r.indexOf(c.type)-r.indexOf(a.type)});(c=0<p.length&&p[0].w>c&&p[0].h>e?p[0].ee:null)&&a&&(c.gc=a.gc);return c};this.$c=function(a,c){this.a("ff10");try{if(!a)return!1;for(c||(c=window);a!=c.document&&a.parentNode;)a=a.parentNode;this.a("ff10e");return a==c.document}catch(e){return!1}};this.cc=function(a,c){var e=c.parent,k={left:0,right:0,top:0,bottom:0};if(a){var g=a.getBoundingClientRect();c!=e&&this.Jb(c,e)&&
(k=this.cc(c.frameElement,e));k={left:g.left+k.left,right:g.right+k.left,top:g.top+k.top,bottom:g.bottom+k.top}}return k};this.Jb=function(a,c){var e=!1;if(a==c)e=!0;else try{a.document.domain==c.document.domain&&(e=!0)}catch(k){}return e};this.re=function(a){if(a)try{if(a.contentDocument&&this.Zc(a.contentDocument))return a.contentDocument;if(a.contentWindow&&this.dd(a.contentWindow))return a.contentWindow.document}catch(c){}return null};this.De=function(a){return a?a.defaultView||a.parentWindow:
null};this.ad=function(a,c){return-1<c.indexOf(a)};this.ke=function(a){try{return a!=a.top&&a.parent&&this.dd(a.parent)?a.parent:null}catch(c){return null}};this.dd=function(a){try{return a&&a.document&&this.Zc(a.document)?!0:!1}catch(c){return!1}};this.Zc=function(a){try{return a&&a.getElementsByTagName&&a.getElementById?!0:!1}catch(c){return!1}};this.yc=function(a,c){var e=c.parent,k={w:0,h:0,left:0,right:0,top:0,bottom:0};a&&(k=this.cc(a,c),k.w=k.right-k.left,k.h=k.bottom-k.top,c!=e&&this.Jb(c,
e)&&(e=this.yc(c.frameElement,e),e.bottom<k.bottom&&(e.bottom<k.top&&(k.top=e.bottom),k.bottom=e.bottom),e.right<k.right&&(e.right<k.left&&(k.left=e.right),k.right=e.right),k.w=k.right-k.left,k.h=k.bottom-k.top));return k};this.Tb=function(a,c){return function(){return a.apply(c,arguments)}};this.ta=function(a){try{return a?a.length?a.length:0:0}catch(c){return 0}};this.ec=function(a){for(var c=[],e=0;e<a.length;e++)this.Oe(a[e])&&c.push(a[e]);return c};this.a=function(a){try{maxLength=3,$dv&&($dv.Ia=
$dv.Ia||[],$dv.Ia.push(a),$dv.Ia.length>maxLength&&$dv.Ia.shift())}catch(c){}};this.mb=function(){try{return $dv&&$dv.Ia?"&dvp_log="+$dv.Ia.join():""}catch(a){return""}};this.wa=function(a){if(a.$sf&&a.$sf.ext)if(a.$sf.ext.geom){if(a=a.$sf.ext.geom(),null!=a&&a.win&&(0<a.win.h||0<a.win.w))return this.wa=function(){return!0},!0}else if(a.$sf.ext.inViewPercentage)return!0;this.wa=function(){return!1};return!1};this.jc=function(a){return a.context&&a.context.observeIntersection?!0:!1};this.qb=function(){var a=
!1;if(1==this.Pa("disableIO"))return!1;"undefined"!=typeof IntersectionObserver&&(a=!0);return a};this.rb=function(a,c,e){var k=e&&e.Enums.BrowserId||window.$dv.Enums.BrowserId;if(a==(e&&e.Enums.TrafficScenario||window.$dv.Enums.TrafficScenario).CrossDomain&&c.V===k.Safari&&(null===c.va||void 0===c.va||!/^[3-8]/.test(c.va)))return this.rb=function(){return!0},!0;this.rb=function(){return!1};return!1};this.Pa=function(a){var c,e=this.Oc();e&&e.AVO&&(c=e.AVO[a]);return c};this.Oc=function(){var a={},
c=window.$dv,e=window.$uid;c.tags&&c.tags[e]&&(a=c.tags[e]);return a};this.Ab=function(){return 1==this.Pa("sam")?!0:!1};this.Ha=new function(){var a=this;a.cache=[];window.addEventListener?a.add=function(c,e,k,g,r){if("undefined"==typeof g||null==g)g=window;g.addEventListener(c,e,k);r&&a.cache.push([c,e,k,g])}:window.attachEvent?a.add=function(c,e,k,g,r){if("undefined"==typeof g||null==g)g=window;g["e"+c+e]=e;g[c+e]=function(){g["e"+c+e](window.event)};g.attachEvent("on"+c,g[c+e]);r&&a.cache.push([c,
e,k,g])}:a.add=function(){};window.removeEventListener?a.remove=function(a,e,k,g){if("undefined"==typeof g||null==g)g=window;g.removeEventListener(a,e,k)}:window.detachEvent?a.remove=function(a,e,k,g){if("undefined"==typeof g||null==g)g=window;g.detachEvent("on"+a,g[a+e]);g[a+e]=null;g["e"+a+e]=null}:a.remove=function(){};a.flush=function(){for(var c=0;c<a.cache.length;c++)a.remove.apply(a,a.cache[c]);a.cache=[]}};this.bc=function(a,c){var e=a||"",k="";if(c&&(e+=": "+(c.message||""),c.stack)){var k=
c.stack||"",g=k.indexOf("at ");0>g&&(g=0);k=", Stack: "+k.slice(g,k.length)}g=null;try{g=encodeURIComponent(e+k).slice(0,500)}catch(r){try{g=encodeURIComponent(e).slice(0,500)}catch(p){g=e.slice(0,500)}}return g}}
function ja(a,c,e,k,g){function r(b,d){for(var a=[],c=0;c<m.length;c++){var e=[];try{e=d(b,m[c])}catch(g){p("s5",g)}var h=f.ta(e);if(0!=h){var k=null;try{k=f.De(m[c])}catch(g){p("s6",g)}if(null!=k)for(var q=0;q<h;q++)e[q].gc=k,a.push(e[q])}}return a}function p(b,d){if(!f.ad(b,q)){q.push(b);var a=$dv&&t.dvObj,c=$uid||(a||{}).impressionId;if(a&&a.registerEventCall&&c&&d&&b){var e={};e.dvp_avstp=q.join("-");e["dvp_"+b+"err"]=f.bc("debug",d);a.registerEventCall(c,e)}}}var t=this,f=new H,v="Microsoft Internet Explorer"==
navigator.appName;this.c=k;this.window=e;this.Cb=[["DCF",'"'],[";",";"],["%3B","%3B"],["zoneid=","_"],["zoneid%3D","_"],["PRImpID=",""],["PRImpID%3D",""],["PRPID=",""],["PRPID%3D",""]];this.oc=[1==v?"object":"embed",1==v?"embed":"object","href","img","span","iframe","frameElement","div"];this.yb=this.f=null;this.dataObj=a;this.dvObj=a.dvObj||window.$dv;this.I={V:this.dvObj.CommonData.BrowserId,va:this.dvObj.CommonData.BrowserVersion};this.W=this.dvObj.Enums.BrowserId;this.O=g;this.X=this.dvObj.Enums.TrafficScenario;
this.$d=function(){var b=this.dataObj.Vb+"-"+this.dataObj.Sb;this.dataObj.isBrandShieldOrigin&&(b+="-bs");return b.replace(RegExp(",","g"),";")};this.sc=this.$d();this.T=c;this.N={R:{h:1,w:1},Af:{h:10,w:10},Ve:10};115==this.dataObj.Ob&&(this.N.R.h=20,this.N.R.w=20);this.dataObj.findclass&&1==this.dataObj.findclass&&this.oc.push("classDeclaration");this.searchByAdSrvId_8=function(b,d){f.a("a1");var a=/[0-9]+-[0-9]+-[0-9]+-[0-9]+/.exec(b);return null!=a&&(a=a.toString(),a.replace(RegExp("-","g"),"")==
d)?!0:!1};this.Wb=this["searchByAdSrvId_"+(this.dataObj?this.dataObj.Ob||"":"")];var q=[];this.getElementsByClassName=function(b,d){try{return r(b,function(b,a){f.a("ff1");var c=a.getElementsByClassName(b);f.a("ff1e");return"1"!=d?c:f.ec(c)})}catch(a){return p("s7",a),[]}};this.querySelectorAll=function(b,d){try{return r(b,function(b,a){f.a("ff3");var c=a.querySelectorAll("."+b);f.a("ff3e");return"1"!=d?c:f.ec(c)})}catch(a){return p("s8",a),[]}};this.getElementsByTagName=function(b,d){try{return r(b,
function(b,a){f.a("ff4");var c=a.getElementsByTagName(b);f.a("ff4e");return"1"!=d?c:f.ec(c)})}catch(a){return p("s9",a),[]}};this.classDeclaration=function(){f.a("a9");var b="undefined"!==typeof window.document.getElementsByClassName,d="undefined"!==typeof window.document.querySelectorAll;if(!(1>this.dataObj.L.length)){var a=[];if(b)a=this.getElementsByClassName(this.dataObj.L,this.dataObj.displaynon);else if(d)a=this.querySelectorAll(this.dataObj.L,this.dataObj.displaynon);else return;b=f.ta(a);
for(d=0;d<b;d++)if(a[d]&&!this.pa(a[d])){this.aa(a[d]);this.f=a[d];break}}};this.div=function(){if(!(1>this.dataObj.L.length))for(var b=this.getElementsByTagName("div",this.dataObj.displaynon),d=f.ta(b),a=0;a<d;a++)if(b[a]&&this.ya(this.dataObj,b[a],!0)&&!this.pa(b[a])){var c=f.na(b[a]);if(c&&c.h>this.N.R.h&&c.w>this.N.R.w){this.f=b[a];this.aa(b[a]);break}else if(this.f=f.Eb(b[a],this.N.R.w,this.N.R.h,f.Tb(f.na,f))){this.aa(this.f);this.aa(b[a]);break}}};this.span=function(){f.a("a10");if(!(1>this.dataObj.L.length))for(var b=
this.getElementsByTagName("span",this.dataObj.displaynon),a=f.ta(b),d=0;d<a;d++)if(b[d]&&this.ya(this.dataObj,b[d],!0)&&!this.pa(b[d])){if(this.Je(b[d])){this.f=b[d];break}if(this.f=f.Eb(b[d],this.N.R.w,this.N.R.h,f.Tb(f.na,f))){this.aa(this.f);this.aa(b[d]);break}}};this.object=function(){f.a("a11");for(var b=this.getElementsByTagName("object",this.dataObj.displaynon),d=f.ta(b),a=0;a<d;a++)if(b[a]&&this.ya(this.dataObj,b[a])&&!this.pa(b[a])&&(this.f=f.Eb(b[a],this.N.R.w,this.N.R.h,f.Tb(f.na,f)))){this.aa(this.f);
this.aa(b[a]);break}};this.embed=function(){f.a("a12");for(var b=this.getElementsByTagName("embed",this.dataObj.displaynon),a=f.ta(b),d=0;d<a;d++)if(b[d]&&this.ya(this.dataObj,b[d])&&!this.pa(b[d])){var c=f.na(b[d]);if(c&&c.h>this.N.R.h&&c.w>this.N.R.w){this.f=b[d];this.aa(b[d]);break}}};this.href=function(){f.a("a13");for(var b=this.getElementsByTagName("a",this.dataObj.displaynon),d=f.ta(b),a=0;a<d;a++)if(b[a]&&this.ya(this.dataObj,b[a])&&!this.pa(b[a])){var c=b[a].getElementsByTagName("img");if(0<
c.length){var e=f.na(c[0]);if(e&&e.h>this.N.R.h&&e.w>this.N.R.w){this.f=c[0];this.aa(b[a]);break}}}};this.img=function(){f.a("a14");for(var b=this.getElementsByTagName("img",this.dataObj.displaynon),a=f.ta(b),d=0;d<a;d++)if(b[d]&&this.ya(this.dataObj,b[d])&&0>b[d].src.indexOf("event")&&!this.pa(b[d])){var c=f.na(b[d]);if(c&&c.h>this.N.R.h&&c.w>this.N.R.w){this.f=b[d];this.aa(b[d]);break}}};this.iframe=function(){f.a("a15");for(var b=this.getElementsByTagName("iframe",this.dataObj.displaynon),d=f.ta(b),
a=0;a<d&&!this.Bc(b[a]);a++);};this.frameElement=function(){f.a("a16");this.O==this.X.SameDomain&&this.Bc(this.window.frameElement)};this.Bc=function(b){f.a("a17");return this.ya(this.dataObj,b)?this.Pd(b):!1};this.aa=function(b){f.a("a18");if(b&&0==this.pa(b)){var d=b.getAttribute("dvvisit");d?b.setAttribute("dvvisit",d+","+this.sc):(f.a("ff5"),d=this.window.document.createAttribute("dvvisit"),f.a("ff5e"),d.value=this.sc,b.setAttributeNode(d))}};this.$e=function(b){b&&b.hasAttribute&&b.hasAttribute("dvvisit")&&
b.removeAttribute("dvvisit")};this.ef=function(){this.$e(this.f);this.f=null};this.pa=function(b){f.a("a19");if(b&&(b=b.getAttribute("dvvisit"))){b=b.split(",");for(var d=0;d<b.length;d++)if(b[d]==this.sc)return!0}return!1};this.Je=function(b){f.a("a20");return b&&"1"==b.getAttribute("adunit")?!0:!1};this.Pd=function(b){f.a("a21");if(b&&!this.pa(b)){var d=f.na(b);if(d&&d.h>this.N.R.h&&d.w>this.N.R.w)return this.f=b,this.aa(b),!0}return!1};this.ya=function(b,d,a){f.a("a22");var c=null;return b.L&&
0<b.L.length&&(this.zc=1==b.Pe?this.Dd:this.Fb,c=this.Jd(b,d,a))||!this.f&&(c=this.Kd(b,d))?!0:!1};this.Jd=function(b,d,a){f.a("a23");var c;try{if(b.Ic&&d&&d.hasAttribute&&d.hasAttribute("dv-view"))return!0;(c=this.za(d.id,b.L))||(c=this.za(d.src,b.L));c||(c=this.za(d.href,b.L));c||(c=this.za(d.getAttribute("flashvars"),b.L));c||(c=this.za(d.name,b.L));c||a||(c=this.za(d.innerHTML,b.L));c&&!a&&(c=this.Id(b,d));return c}catch(e){return c}};this.Kd=function(b,d){f.a("a24");var a;try{if(b.Ic&&d&&d.hasAttribute&&
d.hasAttribute("dv-view"))return!0;(a=this.Ca(d.id,b))||(a=this.Ca(d.src,b));a||(a=this.Ca(d.href,b));a||(a=this.Ca(d.Ff,b));a||(a=this.Ca(d.name,b));a||(a=this.Ca(d.innerHTML,b));return a}catch(c){return a}};this.Ca=function(b,d){f.a("a25");if(!b)return!1;b=b.toLowerCase();for(var a=0;a<this.Cb.length;a++){var c;if(d.Cc&&(c=(this.Cb[a][0]+d.Cc).toLowerCase(),c=b.indexOf(c),-1<c)||d.gd&&(c=(this.Cb[a][0]+d.gd).toLowerCase(),c=b.indexOf(c),-1<c))return!0}return!1};this.Id=function(b,d){f.a("a26");
return null==b.cb||""==b.cb?!1:this.za(this.Cd(d),b.cb)};this.Cd=function(b){f.a("a27");if(b.outerHTML)return b.outerHTML;for(var d=b.attributes.length,a="",c=0;c<d;c++)a=a+b.attributes[c].nodeName+"="+b.attributes[c].nodeValue+" ";return a+b.innerHTML};this.za=function(b,d){f.a("a28");return!b||!d||5>d.length?!1:null!=(this.zc?this.zc(b,d):this.Fb(b,d))?!0:this.Wb&&"function"===typeof this.Wb?this.Wb(b,d):!1};this.Dd=function(d,a){f.a("a29");var c;try{c=(new RegExp(a)).exec(d)}catch(e){c=this.Fb(d,
a)}return c};this.Fb=function(d,a){f.a("a30");var c=null;-1!==d.indexOf(a)&&(c=d);return c};this.ge=function(d){f.a("a31");if(this.te())return this.c.xd(),this.ic||(this.ic=!0),this.f;if(this.dataObj.L&&0<this.dataObj.L.length&&!0===this.ic&&1<d)return this.f;"1"!=this.dataObj.displaynon&&(d=this.ue(),d.node&&(this.c.wd(d.Ga),this.f=d.node));return this.f};var m=[];this.te=function(){f.a("32");if(this.dataObj.L&&0<this.dataObj.L.length){var d=this.oc.length;try{var a=this.window,c=0,e=[];do{try{e.push(a.document)}catch(g){p("s2",
g)}try{for(var h=e,k=a.document.getElementsByTagName("iframe")||[],q=0;q<k.length||25>q;q++){var r=null;try{r=f.re(k[q])}catch(g){p("s1",g)}void 0!==r&&null!==r&&0==f.ad(r,h)&&h.push(r)}}catch(g){p("s3",g)}try{a=f.ke(a)}catch(g){p("s4",g)}}while(a&&10>++c);m=e}catch(g){m=[this.window],p("s0",g)}for(a=0;a<d;a++)if(this[this.oc[a]](),this.f){this.yb=this.f;break}}return this.f};var h=[],d=["object","embed","img","iframe"];this.dataObj.spotXmode&&(d=["object","embed","video","iframe"]);this.Le=function(d){f.a("a33");
d=f.na(d);return this.Me(d)};this.Me=function(d){if(d){var a=d.w;d=d.h;for(var e=c.length,f=0,g=0;g<e;g++)if(15>=Math.abs(a-c[g].w))for(var f=c[g].h.length,h=0;h<f;h++)if(15>=Math.abs(d-c[g].h[h]))return!0}return!1};this.ne=function(){f.a("a34");return this.dataObj.isBrandShieldOrigin?this.oe():this.pe()};this.pe=function(){f.a("a35");var d=(window.name||(window.frameElement?window.frameElement.id:"")).substr(7),a=window.parent;f.a("ff6");a=a.document.getElementsByTagName("script");f.a("ff6e");for(var c=
a.length,e=0;e<c;e++)if(a[e]&&a[e].id&&a[e].id.substr(7)==d)return a[e];return null};this.oe=function(){f.a("a36");return this.dvObj.tags[this.dataObj.impressionId].tagElement};this.ue=function(){f.a("a37");var d=this.ne();return this.Ud(d)};this.Ud=function(a){f.a("a38");var c={node:a,Ga:0};a=[];for(h=[];c||0<a.length;){try{var e;a:{var g=c.node;try{if(g&&-1!=d.indexOf(g.nodeName.toLowerCase())){e=!0;break a}}catch(m){}e=!1}if(e&&this.Le(c.node)&&!this.pa(c.node))return this.aa(c.node),c;if(c.Ga<=
this.N.Ve){var k,q=c.node,p=c.Ga,c=[],r=q.parentNode;r&&-1==h.indexOf(r)&&(h.push(r),c.push({node:r,Ga:p+1}));if(q.hasChildNodes())for(var t=0;t<q.childNodes.length;t++)q.childNodes[t]&&-1==h.indexOf(q.childNodes[t])&&1===q.childNodes[t].nodeType&&(h.push(q.childNodes[t]),c.push({node:q.childNodes[t],Ga:p+1}));var v,I=q,T=[],z=null;I&&I.parentNode&&(z=I.parentNode.firstChild);for(;z;)1===z.nodeType&&z!==I&&T.push(z),z=z.nextElementSibling||z.nextSibling;v=T;for(t=0;t<v.length;t++)v[t]&&-1==h.indexOf(v[t])&&
1===v[t].nodeType&&(h.push(v[t]),c.push({node:v[t],Ga:p+1}));if(k=c)for(c=0;c<k.length;c++)a.push(k[c])}}catch(m){}c=a.shift()}return{node:null}};return this}
function dv_CustomClientViewAssureService(a){function c(a){return{settings:a.settings,buckets:0,reported:!1,eventId:a.eventId,Ka:a.Ka,gb:a.gb}}this.dvObj=a.dvObj||window.$dv;this.impressionId=a.impressionId||window.$uid;this.b=new H;var e=[],k=null,g=null,r=null,p=null;this.dvObj&&this.dvObj.tags&&this.dvObj.tags[this.impressionId]&&(k=this.dvObj.tags[this.impressionId].cvmSettings,g=this.dvObj.tags[this.impressionId].billable,r=this.dvObj.tags[this.impressionId].bprjct,p=this.dvObj.tags[this.impressionId].gmmod);
this.wc=window.dv_cvmSettings||k||a.cvmSettings;this.Pb=window.dv_billable||g||a.billable;this.Hc=window.Hf||r||a.bprjct;this.Uc=window.If||p;this.ae=new c({settings:this.wc,eventId:6,Ka:["CustomViewabilityViewable"]});var t=this.b.Pa("rpv"),k=this.b.Oc().bgm;a.Ta=1==t&&1==k;this.Gc=new c({settings:this.Pb,eventId:17,Ka:a.Ta?["BillableViewedImpression"]:["BillableViewedImpression","GroupMPassedImpression"],gb:!0});this.wc&&e.push(this.ae);this.Pb&&e.push(this.Gc);a.la=a.la||[];k={serverProperties:{projected:"bp",
viewed:"bpv",viewedRate:"bpvr",error:"bperr"},reportQueryString:{projected:"isbprjct",measurems:"isbmms",viewedms:"isbvms",viewrate:"prjctbvr",error:"prjctber"}};this.Hc&&(k={serverData:this.Hc,projectionData:k,reportRTN:!0},a.la.push(k));k={serverProperties:{projected:"gmp",viewed:"gmpv",viewedRate:"gmpvr",error:"gmperr"},reportQueryString:{projected:"isgmmod",measurems:"isgmmims",viewedms:"isgmpims",viewrate:"modgmvr",error:"modgmer"}};this.Uc&&(k={serverData:this.Uc,projectionData:k,reportRTN:!0},
a.la.push(k));this.Td=dv_InViewService;this.Td(a);var f=this.Gb;this.Gb=function(a){a=f(a);for(var c=0;c<e.length;c++){var g=this.Be(a,e[c]);this.wf(g,e[c]);this.Rd(e[c])}return a};var v=this.La;this.La=function(a,c){v(a,c);this.Pb&&1==this.Xb&&(this.xa(["BillableMeasuredImpression"]),t?0==this.dataObj.Ta&&this.xa(["GroupMMeasuredImpression"]):1!=this.dataObj.irtf&&this.xa(["GroupMMeasuredImpression"]))};this.Be=function(a,c){"undefined"===typeof c.settings.focus||c.settings.focus||(a.i=a.ja);return a};
this.wf=function(a,c){(!c.settings.measureType||"consecutive"==String(c.settings.measureType).toLowerCase())&&a.i<c.settings.adArea?c.buckets=0:a.i>=c.settings.adArea&&(!c.gb||1!=this.dataObj.irtf)&&(c.buckets+=this.ba.interval);c.J=a.J};this.Rd=function(a){a.df||a.gb&&1==this.dataObj.irtf||!(this.Ld(a)||a===this.Gc&&a.settings&&!a.settings.doNotReportViewedOnLargeAd&&a.J)||(this.U.$(this.c.ca(a.eventId),a.eventId),a.Ka&&this.xa(a.Ka),a.df=!0)};this.Ld=function(a){return a.buckets>=a.settings.duration?
!0:!1}}
function dv_InViewService(a){function c(){null===g.interval&&(g.interval=setInterval(g.se(),g.ba.interval))}function e(){if(!1===g.cd){g.cd=!0;try{g.b.Ha.remove("load",arguments.callee,!1,element)}catch(a){}g.vb();g.b.a("s41");g.ua=new ia(g.Wd?g.Wd:g.window,g.f,g.O,g.I,g.P,g.c.Rb,g.dvObj,g.impressionId);g.b.a("s42");g.start();g.Fd()}}function k(a,b){g.b.Ha.add("click",function(){g.Kb(!0);$dv.registerEventCall(g.impressionId,"ad"==b?{dvp_csad:1}:{dvp_csifr:1});g.b.Ha.remove("click",arguments.callee,!1,
a)},!1,a,!1)}var g=this;this.fd=10;this.Nb=a.serverSettings&&a.serverSettings.jsVersion?a.serverSettings.jsVersion:"614";this.dvObj=a.dvObj||window.$dv;this.impressionId=a.impressionId||window.$uid;this._minor_version="0";this.b=new H;this.Ce=function(){for(var a=document.getElementsByTagName("script"),b=a.length,c,e=0;e<b;e++)if(c=a[e].src,/visit[.]js/.test(c))return c.substring(c.indexOf("?")+1)};this.cd=!1;var r={serverProperties:{projected:"p",error:"perr",viewed:"pv",featurebit:"fb",viewedRate:"pvr"},
reportQueryString:{projected:"isprjct",measurems:"ismms",viewedms:"isiabvms",viewrate:"prjctvr",error:"prjcter"}},p=!1,t=!1;this.la=a.la||[];(this.xf=a.prjct)&&this.la.push({serverData:a.prjct,projectionData:r,bf:!0,yf:["MeasurementCapabilityDetected","ProjectedMeasured","IabView","ProjectedAssignedViewed"],We:["MeasurementCapabilityDetected","ProjectedMeasured"]});r={serverProperties:{projected:"up",error:"uperr",viewed:"upv",viewedRate:"upvr"},reportQueryString:{projected:"isuprjct",measurems:"isumms",
viewedms:"isuiabvms",viewrate:"uprjctvr",error:"uprjcter"}};this.dvObj&&this.dvObj.tags&&this.dvObj.tags[this.impressionId]&&this.dvObj.tags[this.impressionId].uprjct&&this.la.push({serverData:this.dvObj.tags[this.impressionId].uprjct,projectionData:r});this.xe=function(){var a="";this.dvObj&&this.dvObj.tags&&this.dvObj.tags[this.impressionId]&&this.dvObj.tags[this.impressionId].tagElement&&(a=this.dvObj.tags[this.impressionId].tagElement.src,a=a.substring(a.indexOf("?")+1));return a};this.Tc=function(){return((new Date).getTime()+
""+Math.floor(1E6*Math.random())).substr(0,16)};this.da=function(a,b){a=a.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");var c=(new RegExp("[\\?&]"+a+"=([^&#]*)")).exec("?"+b);return c=c?c[1]:null};this.ze=function(){var a=this.da("uid",this.S);null==a?(a=this.Tc(),this.S=this.S+"&uid="+a):""==a&&(a=this.Tc(),this.S=this.S.replace("&uid=","&uid="+a));return a};this.pc=function(a,b,c,e){if(e&&e.insertBefore&&e.firstChild&&(a=this.window.document.createElement(a))){for(var f in b)a[f]=b[f];for(f in c)a.style[f]=
c[f];e.insertBefore(a,e.firstChild);return a}return null};this.Vd=function(){var a=this.dvObj.Enums.TrafficScenario;try{if(window.top==window)return a.OnPage;if(window.top.document.domain==window.document.domain)return a.SameDomain}catch(b){}return a.CrossDomain};this.O=this.dvObj.CommonData.Scenario||this.Vd();this.I={V:this.dvObj.CommonData.BrowserId,va:this.dvObj.CommonData.BrowserVersion};this.W=this.dvObj.Enums.BrowserId;this.X=this.dvObj.Enums.TrafficScenario;this.Wa="default";this.dataObj=
a;this.window=a.tagWindow||parent.window||window;this.yb=this.f=null;this.vc=this.Na=!1;this.lc=!0;this.interval=null;this.S=this.Ce();this.xb=this.xe();this.Ze=a.serverSettings&&a.serverSettings.protocol&&0==a.serverSettings.protocol.indexOf("http")?a.serverSettings.protocol:window.location.protocol?window.location.protocol+"//":"http://";this.ba=window.de||this.window.de||{interval:100,Aa:{"default":{time:null,Ha:["beforeunload","unload"],sd:9E5}}};this.hd={};var r="tps300.doubleverify.com",f=null;
try{this.dvObj.tags[this.impressionId].ServerPublicDns&&(r=this.dvObj.tags[this.impressionId].ServerPublicDns)}catch(d){}this.ha=window.dv_configServer||this.window.dv_configServer||{protocol:this.Ze,port:"",domain:r,api:"event.jpg"};this.Z=window.ce||this.window.ce||{interval:1E3,ka:6};r=a&&a.ud?a.ud:!1;a=a&&a.vd?a.vd:!1;!1!==r&&!1!==a&&(this.Z.interval=r,this.Z.ka=a,$dv.registerEventCall(this.impressionId,{Df:this.Z.interval,Ef:this.Z.ka}));this.Zd={eb:12,Zb:10,Ua:30};this.P={Firefox:{Y:115},Chrome:{Y:89},
Safari:{Y:38},Explorer:{Y:55},Xe:500,Ua:30};var v=!1,q=0,m=[5,10,15];window.devicePixelRatio&&(this.P.Firefox.Y=0);this.dataObj.spotXmode=this.dataObj.videoEnable||this.dataObj.detectVideoPlayer||this.dataObj.spotXmode;this.dvObj&&this.dvObj.tags&&this.dvObj.tags[this.impressionId]&&this.dvObj.tags[this.impressionId].spotXmode&&(this.dataObj.spotXmode=this.dvObj.tags[this.impressionId].spotXmode);this.T=window.dv_configAdSize||this.window.dv_configAdSize||[{w:300,h:[100,250,268,600,618,850,1050]},
{w:160,h:[600,800]},{w:120,h:[60,90,240,600,800]},{w:970,h:[66,90,250,30,415,550]},{w:728,h:[90,120]},{w:88,h:[31]},{w:700,h:[500]},{w:250,h:[60,250,300]},{w:180,h:[150,160,600]},{w:234,h:[60]},{w:468,h:[60]},{w:550,h:[480]},{w:125,h:[125]},{w:336,h:[280,600,850]},{w:745,h:[90]},{w:954,h:[60]},{w:184,h:[90]},{w:800,h:[600]},{w:320,h:[360,50]},{w:1280,h:[100]},{w:640,h:[480,90]},{w:270,h:[460,202]},{w:613,h:[460]},{w:405,h:[303]},{w:950,h:[90]},{w:610,h:[100]},{w:272,h:[220]}];this.dataObj.spotXmode&&
(this.T.push({w:320,h:[240]}),this.T.push({w:400,h:[300]}),this.T.push({w:450,h:[338]}),this.T.push({w:600,h:[800]}),this.T.push({w:640,h:[360]}),this.T.push({w:854,h:[480]}),this.T.push({w:500,h:[375]}));$dv&&$dv.CommonData&&(2==$dv.CommonData.deviceType||3==$dv.CommonData.deviceType)&&(this.T.push({w:320,h:[480]}),this.T.push({w:300,h:[50]}),this.T.push({w:120,h:[20]}),this.T.push({w:168,h:[28]}),this.T.push({w:216,h:[36]}));this.Vc=this.ze();this.Yb=!1;this.Db=function(a,b){this.window.Lc||(this.window.Lc=
[]);this.window.Lc.push({caller:a,Gf:b})};this.startTime=(new Date).getTime();this.Qd=4;this.Ac=0;this.fc=!0;this.logEvents={startMeasure:1,nonMeasurable:2,timeout:3,beforeunload:4,iabViewable:5,iabCustom:6,updateRTN:7,unload:8,projection:9,fraudMeasured:10,errorlevel1:16,Bf:17,interval:32};this.Xb=!1;this.td=function(){this.b.a("ie16");if(this.window.dv_logObject){var a=this.c.le();this.window.dv_logObject[this.Vc]=a}this.b.a("ie16e")};this.zb=function(a){this.b.a("ie17");this.zb=this.Yb?function(a){this.c.nd(a);
this.td()}:function(a){this.c.nd(a)};this.zb(a)};this.uc=function(a,b){this.uc=this.Yb?function(a,d){this.c.md(a,d);this.td()}:function(a,d){this.c.md(a,d)};this.uc(a,b)};this.vb=function(){this.b.a("s4");this.f=this.ab.ge(this.Z.ka);this.yb=this.ab.yb;!this.f&&this.O==this.X.CrossDomain&&this.b.wa(this.window)&&(this.Z.ka=0);this.f?(this.gf(),this.c.af(this.f),p||(k(this.f,"ad"),p=!0),t||this.O!=this.X.CrossDomain&&this.O!=this.X.SameDomain||(k(window.parent,"ifr"),t=!0),setTimeout(c,this.ab.ic?
10:50)):0<this.Z.ka?(this.Z.ka--,this.hf(),setTimeout(this.he(),this.Z.interval)):(this.O==this.X.CrossDomain&&(this.b.ed(this.window,this.T)||this.b.wa(this.window))?(this.f=this.b.Qa(this.window),this.c.ld()):this.O==this.X.SameDomain&&this.b.ed(this.window,this.T)?(this.f=this.b.Qa(window.parent),this.c.ld(),this.Yd()):this.Z.ka=-1,setTimeout(c,10));this.b.a("s4e")};this.Yd=function(){for(var a=this.window;a.parent!=a.top;)a=a.parent;this.b.a("ff26");for(var b=a.parent.document.getElementsByTagName("iframe"),
c=b.length,e=0;e<c;e++)b[e].contentWindow==a&&(this.f=b[e],this.window=a.parent);this.b.a("ff26e")};this.hf=function(){this.dataObj.L&&this.dataObj.cb?this.c.mf():this.c.nf()};this.gf=function(){this.b.a("s9");this.Na=!0;this.c.jf();this.b.a("s9e")};this.Sd=function(){this.dataObj.Ob=this.da("adsrv",this.S)||"";this.dataObj.L=this.da("btreg",this.S)||"";this.dataObj.gd=this.da("plcid",this.S)||"";"8"==this.dataObj.Ob&&""==this.dataObj.btreg&&(this.dataObj.L=this.dataObj.plcid);this.dataObj.cb=this.da("btadsrv",
this.S)||"";this.dataObj.Cc=this.da("adid",this.S)||"";this.dataObj.Pe=this.da("isbtregex",this.xb)||"";this.dataObj.Vb=this.da("ctx",this.S)||"";this.dataObj.Sb=this.da("cmp",this.S)||"";this.dataObj.Re=this.da("lomd",this.S)||"";this.dataObj.findclass=this.da("findclass",this.xb)||"";this.dataObj.displaynon=this.da("displaynon",this.xb)||"";this.dataObj.Ic=this.da("bsdvview",this.xb)||""};this.Va=function(a){a=this.xa(a);return 0<a.length?"&tagServiceResult="+encodeURIComponent(a.join(",")):""};
this.xa=function(a){if(!this.dvObj||!this.impressionId)return[];for(var b=[],c=0;c<a.length;c++){var e=this.dvObj.pubSub.publish(a[c],this.impressionId)||null;null!=e&&b.push(e)}return b};this.Ge=function(a){1==a&&(this.c.uf(),this.dvObj&&this.impressionId&&this.c.kc()&&(a=this.Va(["MeasurementCapabilityDetected","GeoMeasured"]),this.U.$(this.c.ca(this.logEvents.fraudMeasured)+a,this.logEvents.fraudMeasured)))};this.Fe=function(a){var b="",c=a.serverData,e=a.projectionData;1==c[e.serverProperties.featurebit]&&
(b=1==c[e.serverProperties.viewed]?this.Va(a.yf):this.Va(a.We));return b};this.yd=function(){this.dataObj.serverSettings&&this.dataObj.serverSettings.TKH&&(this.S+="&TKH="+this.dataObj.serverSettings.TKH)};this.be=function(){Array.prototype.indexOf=function(a){if(null==this)throw new TypeError;var b=Object(this),c=b.length>>>0;if(0===c)return-1;var e=0;1<arguments.length&&(e=Number(arguments[1]),e!=e?e=0:0!=e&&Infinity!=e&&-Infinity!=e&&(e=(0<e||-1)*Math.floor(Math.abs(e))));if(e>=c)return-1;for(e=
0<=e?e:Math.max(c-Math.abs(e),0);e<c;e++)if(e in b&&b[e]===a)return e;return-1}};this.inViewManager=function(){try{Array.prototype.indexOf||this.be();var a=this.ha.protocol+this.ha.domain+this.ha.port+"/"+this.ha.api;this.yd();this.c=new aa(this.Nb,this.S,a,this.Zd,this.dataObj);var b=new ba(this.window,this.Vc);this.dataObj.isReportingDisabled?(ca.prototype=b,this.U=new ca):this.U=b;this.dataObj.isRTNsDisabled&&(this.xa=function(){return[]});this.Yb=this.window.dv_logObject?!0:!1;this.pf();if(!this.c.Rb()&&
(this.Ee(),void 0!=this.dataObj.prjct&&1==this.dataObj.prjct.p&&1==this.dataObj.prjct.fb))return;this.Ge(this.dataObj.irtf);this.Sd();this.ab=new ja(this.dataObj,this.T,this.window,this.c,this.O);var c=window.parent;"589953"==this.dataObj.Vb&&"587351"==this.dataObj.Sb||"589953"==this.dataObj.Vb&&"616389"==this.dataObj.Sb||"polite"==this.dataObj.Re?(setTimeout(e,15E3),this.b.Ha.add("load",function(){setTimeout(e,1E3)},!1,c,!1)):e()}catch(f){var g=this;this.Ma(function(){g.Db("inViewManager",f);g.c.qc("inViewManager",
f);g.U.$(g.c.ca(g.logEvents.errorlevel1),g.logEvents.errorlevel1)},"inViewManager",f)}};this.Ee=function(){for(var a="",b=0;b<this.la.length;b++){var c=this.la[b];this.c.sf(c.serverData,c.projectionData);!0===c.bf&&(a+=this.Fe(c))}0<this.la.length&&this.U.$(this.c.ca(this.logEvents.projection)+a,this.logEvents.projection)};this.Za=function(a){this.b.a("ie20");-6!=a.i&&(-3==a.i||-5!=a.i&&0>a.i&&-1==this.Z.ka)&&(this.xc(),this.Za=function(){})};this.xc=function(){this.U.$(this.c.ca(this.logEvents.nonMeasurable),
this.logEvents.nonMeasurable);this.xa(["ImpressionNotMeasured"]);this.xc=function(){}};this.La=function(a,b){a.b.a("ie21");if(0<=b.i||-5==b.i&&-1>=a.Z.ka){if(a.dvObj&&a.impressionId&&0==a.c.kc()){a.b.a("ie23");var c=a.Va(["MeasurementCapabilityDetected","GeoMeasured"]);a.b.a("ie24");var e=a.c.ca(a.logEvents.startMeasure);a.U.$(e+c,a.logEvents.startMeasure)}else a.U.$(a.c.ca(a.logEvents.startMeasure),a.logEvents.startMeasure);a.Xb=!0;a.La=function(){};a.Za=function(){}}a.b.a("ie22")};this.Kb=function(a){this.b.a("ie25");
if(this.c.Pc()||a&&!0===a)this.b.a("ie27"),this.dvObj&&this.impressionId&&0==this.c.kc()?(this.b.a("ie28"),a=this.Va(["IabView","GeoViewed"]),this.b.a("ie29"),this.U.$(this.c.ca(this.logEvents.iabViewable)+a,this.logEvents.iabViewable)):this.U.$(this.c.ca(this.logEvents.iabViewable),this.logEvents.iabViewable),v=!0,this.Kb=function(){};this.b.a("ie26")};this.acumulateViewableTime=function(a){if(v&&this.c.Pc())for(q+=a,a=0;a<m.length;a++)null!=m[a]&&q>=1E3*m[a]&&(this.xa(["viewd"+m[a]+"sec"]),m[a]=
null)};var h="hidden";this.hasFocus=function(){vis=["hidden","webkitHidden","mozHidden","msHidden","oHidden"];for(hiddenProp in vis)if(vis[hiddenProp]in document){h=vis[hiddenProp];break}this.hasFocus=1==this.b.Pa("fcs")&&this.I.V==this.W.IE&&document.hasFocus?function(){var a=this.window.document.hasFocus();this.O==this.X.OnPage&&(a=a&&this.lc);return a}:1==this.b.Pa("fcs")&&this.O!=this.X.CrossDomain&&document.hasFocus?function(){var a=!0,a=this.window.top.document.hasFocus();document.hasFocus&&
this.O==this.X.OnPage&&(a=a&&this.lc);return a}:"undefined"!==typeof document[h]?function(){return!this.window.document[h]}:document.hasFocus&&this.O!=this.X.CrossDomain?function(){return this.window.top.document.hasFocus()}:function(){return!0};return this.hasFocus()};this.dc=function(a){var b=a.ua.qe();a.b.a("ie12");null==this.f||-3==b.i||a.hasFocus()||(b.i=0);a.b.a("ie13");return f=b};this.Gb=function(a){a.b.a("ie1");var b=a.f?a.f.gc||a.window:a.window;a.ua.f=a.f;a.ua.window=b;a.b.a("ie2");b=a.dc(a);
!a.Na||-1!=b.i&&-2!=b.i||(a.kd(a),a.vb());a.b.a("ie3");-5==b.i&&(a.Z.ka--,a.c.od(),a.Ja||(a.Ja=function(b){b=a.ua.pb(b);a.c.Ya(b)}));a.b.a("ie4");a.Ja&&0<b.i&&(a.Ja(b),a.Ja=null);a.b.a("ie5");if(a.Na&&!a.vc){a.vc=!0;var c=a.ua.pb(b);a.c.Ya(c)}-5==b.i&&(a.kd(a),a.vb(),b=a.dc(a),-5==b.i&&0<a.Z.ka&&a.c.ff());a.b.a("ie6");a.uc(b,a.ba.interval);a.b.a("ie7");a.zb(b);a.b.a("ie8");a.c.qd(b.fa);a.Za(b);a.b.a("ie9");a.La(a,b);a.b.a("ie10");a.Kb();a.b.a("ie11");a.acumulateViewableTime(a.ba.interval);a.b.a("ie12");
return b};this.kd=function(a){a.Na=!1;a.f=null;a.ab.ef();a.ua.He()};this.se=function(){this.b.a("s26");var a=this;return function(){try{a.Gb(a)}catch(b){a.Ma(function(){a.Ac<a.Qd&&(a.Ac++,a.Db("getIntervalCallback",b),a.c.qc("getIntervalCallback",b),a.U.$(a.c.ca(a.logEvents.errorlevel1),a.logEvents.errorlevel1))},"getIntervalCallback",b)}}};this.Sc=function(a){var b=this;return function(){b.Ma(function(){b.I.V==b.W.IE?b.U.$(b.c.ca(b.logEvents[a]),b.logEvents[a]):b.U.tc(b.c.ca(b.logEvents[a]),b.logEvents[a])},
"getReportEventCallback")}};this.he=function(){var a=this;return function(){a.Ma(function(){a.vb();a.f||a.c.wb()},"getAdLocateCallback")}};this.Ra=function(){var a=this;return function(b){try{b||(b=a.window.event),a.lc="blur"==b.type||"focusout"==b.type?!1:!0}catch(c){try{b=callerName||"unknown caller";var e="";a.b?e=a.b.mb():this.b&&(e=this.b.mb());var f=this.ha.protocol+this.ha.domain+this.ha.port+"/"+this.ha.api+"?"+this.S+"&ctime="+(new Date).getTime()+"&evid="+this.logEvents.errorlevel1+"&jsver="+
this.Nb+e+"&napr="+b+": "+c.message;(new Image).src=f}catch(g){}}}};this.Ed=function(){try{if(this.dvObj&&this.impressionId&&this.dvObj.tags[this.impressionId]){var a=this;this.dvObj.tags[this.impressionId].getViewabilityData=function(){try{for(var b=a.c.me().slice(0),c=0;c<b.length;c++)void 0===b[c]||null===b[c]?b[c]=0:isNaN(b[c])||(b[c]/=1E3);var e={};e.bucket_0=b[0];e.bucket_1_9=b[1];e.bucket_100=b[11];for(c=2;10>=c;c++)e["bucket_"+(10*(c-1)).toString()+"_"+(10*c-1).toString()]=b[c];return{buckets:e,
isAdMeasureable:a.Xb,totalPageTime:(a.c.jb()-a.c.we())/1E3,notApplicableTime:a.c.Rc()/1E3}}catch(f){return{}}}}}catch(b){}};this.Fd=function(){try{if(this.dvObj&&this.impressionId&&this.dvObj.tags[this.impressionId]){var a=this.dvObj.tags[this.impressionId];a.VA||(a.VA={});a.VA.getVisibilityResult=function(){var a={};a.perc=f.i;0<=f.i&&f.K&&f.K.j&&(a.adWidth=f.K.j.o,a.adHeight=f.K.j.m);return a}}}catch(b){}};this.Ed();this.start=function(){this.b.a("s35");this.Ye(this);var a;this.ba&&this.ba.Aa&&
this.ba.Aa[this.Wa]&&(a=this.ba.Aa[this.Wa].Ha);if(a)for(var b=a.length,c=0;c<b;c++)this.hd[a[c]]=this.Sc(a[c]),this.Fa(this.window,a[c],this.hd[a[c]]);this.rf();this.ba&&this.ba.Aa&&this.ba.Aa[this.Wa]&&this.ba.Aa[this.Wa].sd&&setTimeout(this.cf(),this.ba.Aa[this.Wa].sd)};this.cf=function(){var a=this;return function(){a.Sc("timeout")();clearInterval(a.interval);a.U.tc=function(){};a.U.$=function(){}}};this.Ye=function(a){try{var b=a.dc(a);-5==b.i&&(this.c.od(),this.Ja||(this.Ja=function(b){b=a.ua.pb(b);
a.c.Ya(b)}));if(a.Na)if(this.vc=!0,-5!=b.i){var c=a.ua.pb(b);a.c.Ya(c)}else a.c.Ya("true");a.c.qd(b.fa);var e=a.ua.je(b,a.c.Rc());a.c.lf(e);a.c.pd(b.i);a.zb(b);a.Za(b);a.La(a,b)}catch(f){a.Ma(function(){a.Db("onStartReport",f);a.c.qc("onStartReport",f);a.U.$(a.c.ca(a.logEvents.errorlevel1),a.logEvents.errorlevel1)},"onStartReport",f)}};this.rf=function(){this.Fa(this.window,"blur",this.Ra());this.Fa(this.window,"focus",this.Ra());this.Fa(this.window.document,"click",this.Ra());this.Fa(this.window.document,
"mousedown",this.Ra());this.Fa(this.window.document,"mouseup",this.Ra())};this.Fa=function(){function a(b,c,e){a=b.addEventListener?function(a,b,c){a.addEventListener(b,c,!1)}:b.attachEvent?function(a,b,c){a.attachEvent("on"+b,c)}:function(a,b,c){a["on"+b]=c};a(b,c,e)}return function(b,c,e){a(b,c,e)}}();this.stop=function(){};this.pf=function(){this.b.a("ff24");this.O==this.X.CrossDomain?this.b.wa(this.window)||this.b.jc(this.window)||this.b.qb()||this.b.rb(this.O,this.I,this.dvObj)||(this.I.V!=this.W.Firefox&&
this.I.V!=this.W.IE?this.c.qf():this.I.V==this.W.Firefox&&"undefined"===typeof this.window.mozInnerScreenX&&this.c.rc()):window.document.body.getBoundingClientRect||this.c.rc();this.fc=this.c.Rb();this.b.a("ff24e")};this.Ma=function(a,b,c){try{a()}catch(e){try{if(0<this.fd){this.fd--;var f=this.b.mb(),g=this.b.bc(b||"unknown caller",c||e),h=this.ha.protocol+this.ha.domain+this.ha.port+"/"+this.ha.api+"?"+this.S+"&ctime="+(new Date).getTime()+"&evid="+this.logEvents.errorlevel1+"&jsver="+this.Nb+f+
"&napr="+g;(new Image).src=h}}catch(k){}}};return this}
try{window.dv_InViewService=dv_InViewService;dv_InViewService.prototype.inViewManager=dv_InViewService.prototype.inViewManager;var ViewAssureBootstrapper=function(a){$dv.tags[$uid].gmmod||$dv.tags[$uid].cvmSettings||$dv.tags[$uid].billable||a.cvmSettings||a.billable?(new dv_CustomClientViewAssureService(a)).inViewManager():(new dv_InViewService(a)).inViewManager()};if("function"===typeof window.IVCallback)IVCallback(ViewAssureBootstrapper);else for(var ka=[window.$dvbs,window.$dvbsr],Y=0;Y<ka.length;Y++){var dvObj=
ka[Y];if(dvObj&&"object"===typeof dvObj&&"function"===typeof dvObj.getTagObjectByService){var tagObject=dvObj.getTagObjectByService("avs614");if(tagObject){var serviceParams=tagObject.services.avs614;serviceParams&&serviceParams.params&&ViewAssureBootstrapper(serviceParams.params)}}}}catch(a){};
